services:
  app:
    container_name: chat_gpt
    image: streamlit-mysql
    ports:
      - 8501:8501

  mysql:
    container_name: mysql_db
    image: mysql:8.2.0
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=my_password
      - MYSQL_DATABASE=chat

volumes:
  mysql-data: